services:
  api-evo:
    container_name: evolution_api
    image: atendai/evolution-api:homolog
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 55291:55291
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 55291

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis-evo
    command: >
      redis-server --port 6380 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6380:6380

  postgres:
    container_name: postgres-evo
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-p 5433", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_USER=user
      - POSTGRES_DB=evolution
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5433

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge
